# Every input, typed and described. The contract is fixed by AWS_DEPLOY_PLAN §A2.2.
#
# Note what is deliberately NOT here: the database password. It is generated by
# `random_password.db` (rds.tf) rather than supplied, so no human ever types it and
# it never lands in a shell history or a tfvars file. The tradeoff — it lands in
# state instead — is stated plainly in README §State honesty.

variable "region" {
  description = "AWS region. Pinned to us-west-2 (Oregon): closest sane region to LA; us-west-1 is pricier with fewer AZs."
  type        = string
  default     = "us-west-2"
}

variable "home_cidr" {
  description = "The operator's home IP as a /32. This is the ONLY ingress on the ALB and the only non-VPC ingress on RDS — it is what makes a live Anthropic key behind a public URL safe (§0.2 invariant 4). If your ISP rotates it: re-run `curl -s ifconfig.me`, update tfvars, apply (~20s)."
  type        = string

  validation {
    condition     = can(cidrnetmask(var.home_cidr)) && endswith(var.home_cidr, "/32")
    error_message = "home_cidr must be a single host CIDR ending in /32 (e.g. \"203.0.113.7/32\")."
  }
}

variable "deployed_git_sha" {
  description = "12-char commit SHA of the deployed tree. Injected as GITHUB_SHA so eval rows written on AWS are attributable to the exact commit — the image has no git binary and the runner falls back to this env var, else records NULL (V11)."
  type        = string

  validation {
    condition     = can(regex("^[0-9a-f]{12}$", var.deployed_git_sha))
    error_message = "deployed_git_sha must be exactly 12 lowercase hex characters (`git rev-parse --short=12 HEAD`)."
  }
}

variable "api_cpu" {
  description = "Fargate CPU units for the API task. 1024 = 1 vCPU."
  type        = number
  default     = 1024
}

variable "api_memory" {
  description = "Fargate memory (MiB) for the API task. 8 GB: lazily-loaded torch plus both retrieval models plus connection-pool headroom (V12)."
  type        = number
  default     = 8192
}

variable "ui_cpu" {
  description = "Fargate CPU units for the UI task. 256 = 0.25 vCPU; it is a static Next.js standalone server."
  type        = number
  default     = 256
}

variable "ui_memory" {
  description = "Fargate memory (MiB) for the UI task."
  type        = number
  default     = 512
}

variable "eval_cpu" {
  description = "Fargate CPU units for the one-off eval task. 2048 = 2 vCPU for concurrency-4 agent loops plus the reranker on CPU."
  type        = number
  default     = 2048
}

variable "eval_memory" {
  description = "Fargate memory (MiB) for the eval task."
  type        = number
  default     = 8192
}

variable "image_tag" {
  description = "Tag pushed to both ECR repos and referenced by all three task definitions."
  type        = string
  default     = "latest"
}
